
name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: apisentinel
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s --health-timeout=5s --health-retries=5
    
    env:
      # CI/Test Environment Variables - NOT FOR PRODUCTION USE
      NODE_ENV: test
      
      # Database connection for CI
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/apisentinel
      
      # Test-only secrets (randomly generated for CI, not production values)
      JWT_SECRET: ci_test_jwt_secret_not_for_production_use_abc123def456
      TOKEN_ENCRYPTION_KEY: ci_test_encryption_key_32_chars_1234567890abcdef1234567890abcdef
      
      # GitHub OAuth test credentials (disabled/mock values)
      GITHUB_OAUTH_CLIENT_ID: ci_test_github_client_id
      GITHUB_OAUTH_CLIENT_SECRET: ci_test_github_client_secret
      
      # Disable optional services in CI
      SENDGRID_API_KEY: ""
      OPENAI_API_KEY: ""
      
      # CI-specific settings
      LOG_LEVEL: error
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 1000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          # Try npm ci first, fallback to npm install if lock file is out of sync
          npm ci || (echo "Lock file out of sync, using npm install" && npm install)
      
      - name: Run linting and type checking
        run: npm run check
        
      - name: Run tests
        run: npm test
        
      - name: Build application
        run: npm run build
        
       - name: Run security audit
         run: npm ci && npm audit --audit-level moderate
         continue-on-error: true
